name: Build and Deploy Docker App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:latest docker/app
      - name: Run tests
        run: echo "Run tests here"
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:latest
      - name: Deploy
        run: echo "Deploy to Kubernetes or cloud here" 